version: '3.8'

services:
  hrms-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./hrms_poc.db
      - PYTHONPATH=/app
    volumes:
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./backend/hrms_poc.db:/app/backend/hrms_poc.db
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add PostgreSQL for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: hrms
  #     POSTGRES_USER: hrms_user
  #     POSTGRES_PASSWORD: hrms_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  # postgres_data:
  # redis_data: 